---
title: "Advent of Code 2022"
author: "Bailey Sutton"
date: "12/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(rstatix)
library(stringi)

library(readr)
```

```{r Day 1}

#import
day1 <- data.table::fread("~/Desktop/Projects/Stats/Advent of Code 2022/Day1.txt")

#reformat dataframe
day1_groups <- day1 %>%
  group_split(grp = cumsum(rowSums(is.na(.)) == ncol(.)), .keep = FALSE) %>%
  map_at(.at = -1, tail, -1)

day1_groups <- data.frame(t(sapply(day1_groups,c)))

day1_groups_long <- day1_groups %>% pivot_longer(everything())

day1_groups_long$value <- stri_replace_all_fixed(day1_groups_long$value, "c(", "")
day1_groups_long$value <- stri_replace_all_fixed(day1_groups_long$value, ")", "")

#separate cals
day1_labs <- separate_rows(day1_groups_long, value, sep = ", ", convert = TRUE)

#summarize by group
day1_labs_tot <- day1_labs %>%
  group_by(name) %>%
  summarise(total = sum(value))

#pull highest total
day1_labs_tot <- day1_labs_tot[order(day1_labs_tot$total),]
tail(day1_labs_tot, n = 1)

#pull total of highest three
day1_labs_tot %>% 
  tail(n = 3) %>%
  pull(total) %>%
  sum()
```

```{r Day 2}

#import
day2 <- read_table2("~/Desktop/Projects/Stats/Advent of Code 2022/day2.txt", col_names = FALSE)

#replace obs names
day2$X1 <- gsub("A", "Rock", day2$X1)
day2$X1 <- gsub("B", "Paper", day2$X1)
day2$X1 <- gsub("C", "Scissors", day2$X1)

day2$X2 <- gsub("X", "Rock", day2$X2)
day2$X2 <- gsub("Y", "Paper", day2$X2)
day2$X2 <- gsub("Z", "Scissors", day2$X2)

#calculate choice score
day2$choice_score <- as.numeric(ifelse(day2$X2 == 'Rock', '1',
                                       ifelse(day2$X2 == 'Paper', '2', '3')))

#calculate win score
day2$win_score <- as.numeric(ifelse(day2$X1 == 'Rock' & day2$X2 == 'Rock', '3',
                                    ifelse(day2$X1 == 'Scissors' & day2$X2 == 'Rock', '6',
                                           ifelse(day2$X1 == 'Paper' & day2$X2 == 'Paper', '3',
                                                  ifelse(day2$X1 == 'Rock' & day2$X2 == 'Paper', '6',
                                                         ifelse(day2$X1 == 'Scissors' & day2$X2 == 'Scissors', '3',
                                                                ifelse(day2$X1 == 'Paper' & day2$X2 == 'Scissors', '6', '0')))))))

#calculate total score
day2$total_score <- day2$choice_score + day2$win_score

#final total
sum(day2$total_score)

#X2 new
day2$X2_new <- ifelse(day2$X2 == 'Rock', 'Lose',
                      ifelse(day2$X2 == 'Paper', 'Draw', 'Win'))

#calculate new choice
day2$choice_new <- ifelse(day2$X1 == 'Rock' & day2$X2_new == 'Win', 'Paper',
                          ifelse(day2$X1 == 'Rock' & day2$X2_new == 'Draw', 'Rock',
                                 ifelse(day2$X1 == 'Rock' & day2$X2_new == 'Lose', 'Scissors',
                                        ifelse(day2$X1 == 'Paper' & day2$X2_new == 'Win', 'Scissors',
                                               ifelse(day2$X1 == 'Paper' & day2$X2_new == 'Draw', 'Paper',
                                                      ifelse(day2$X1 == 'Paper' & day2$X2_new == 'Lose', 'Rock',
                                                             ifelse(day2$X1 == 'Scissors' & day2$X2_new == 'Win', 'Rock',
                                                                    ifelse(day2$X1 == 'Scissors' & day2$X2_new == 'Draw', 'Scissors', 'Paper'))))))))

#calculate new choice score
day2$choice_score_new <- as.numeric(ifelse(day2$choice_new == 'Rock', '1',
                                           ifelse(day2$choice_new == 'Paper', '2', '3')))

#calculate new win score
day2$win_score_new <- as.numeric(ifelse(day2$X2_new == 'Win', '6',
                                        ifelse(day2$X2_new == 'Draw', '3', '0')))

#calculate new total score
day2$total_score_new <- day2$choice_score_new + day2$win_score_new

#calculate new total
sum(day2$total_score_new)
```

```{r Day 3}

#import
day3 <- read_csv("~/Desktop/Projects/Stats/Advent of Code 2022/day3.txt", col_names = FALSE)

#split strings in half
len <- nchar(day3$X1)
half_len <- len/2
half_len_pl1 <- half_len + 1

day3$first_half <- substr(day3$X1,1,half_len)
day3$sec_half <- substr(day3$X1,half_len_pl1,len)

#find duplicate
day3$dups <- str_extract(day3$first_half, paste0("[", day3$sec_half, "]+"))

day3$dup_single <- substr(day3$dups, 1, 1)

#convert letters to numbers
lower_val <- as.numeric(seq(1,26))
upper_val <- as.numeric(seq(27,52))

lower <- letters[1:26]
upper <- LETTERS[1:26]

lower_let_val <- as.data.frame(cbind(lower, lower_val))
upper_let_val <- as.data.frame(cbind(upper, upper_val))

lower_let_val <- lower_let_val %>% rename(letter = lower, val = lower_val)
upper_let_val <- upper_let_val %>% rename(letter = upper, val = upper_val)

let_val <- rbind(lower_let_val, upper_let_val)
let_val$val <- as.numeric(let_val$val)

day3_dup <- as.data.frame(subset(day3, select = c("dup_single")))

day3_dup_val <- left_join(day3_dup, let_val, by = c("dup_single" = "letter"))

#total
sum(day3_dup_val$val)

#group every third obs
day3_grp <- subset(day3, select = c("X1"))

id_len <- 3

day3_grp$id <- as.factor(rep(seq(1, 1 + nrow(day3_grp) %/% id_len), each = id_len, length.out = nrow(day3_grp)))

day3_grp <- day3_grp %>% 
  group_by(id) %>%
  mutate(obs_id = match(X1, unique(X1)))

day3_grp_wide <- pivot_wider(day3_grp, id_col = id, names_from = obs_id, values_from = X1)

#find duplicate
day3_grp_wide$dups_1 <- as.character(str_extract_all(day3_grp_wide$`1`, paste0("[", day3_grp_wide$`2`, "]+")))
day3_grp_wide$dups_2 <- as.character(str_extract_all(day3_grp_wide$`2`, paste0("[", day3_grp_wide$`3`, "]+")))

day3_grp_wide$dups_1 <- stri_replace_all_fixed(day3_grp_wide$dups_1, "c(", "")
day3_grp_wide$dups_1 <- stri_replace_all_fixed(day3_grp_wide$dups_1, ")", "")
day3_grp_wide$dups_1 <- stri_replace_all_fixed(day3_grp_wide$dups_1, ",", "")
day3_grp_wide$dups_1 <- stri_replace_all_fixed(day3_grp_wide$dups_1, " ", "")
day3_grp_wide$dups_2 <- stri_replace_all_fixed(day3_grp_wide$dups_2, "c(", "")
day3_grp_wide$dups_2 <- stri_replace_all_fixed(day3_grp_wide$dups_2, ")", "")
day3_grp_wide$dups_2 <- stri_replace_all_fixed(day3_grp_wide$dups_2, ",", "")
day3_grp_wide$dups_2 <- stri_replace_all_fixed(day3_grp_wide$dups_2, " ", "")

day3_grp_wide <- as.data.frame(sapply(day3_grp_wide, function(x) gsub("\"", "", x)))

day3_grp_wide$dups_all <- str_extract(day3_grp_wide$dups_1, paste0("[", day3_grp_wide$dups_2, "]+"))

day3_grp_wide$dup_single <- substr(day3_grp_wide$dups_all, 1, 1)

#add values
day3_grp_val <- left_join(day3_grp_wide, let_val, by = c("dup_single" = "letter"))

#total
sum(day3_grp_val$val)
```

